version: "3.3"

services:
  db:
    image: mysql
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
