import "@/styles/globals.css";

import * as React from "react";
import { Inter } from "next/font/google";
import { headers } from "next/headers";

import type { Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  metadataBase: new URL("http://localhost:3000/"),
  title: "Flashcard",
  description: "Generated by create-t3-app",
  icons: [
    {
      rel: "icon",
      url: "/t3-light.svg",
      media: "(prefers-color-scheme: light)",
    },
    {
      rel: "icon",
      url: "/t3-dark.svg",
      media: "(prefers-color-scheme: dark)",
    },
  ],

  // Open Graph
  openGraph: {
    type: "website",
    locale: "en_US",
    title: "Flashcard",
    description: "A flashcard app built with T3",
    url: "http://localhost:3000/",
    images: [
      {
        url: "/t3-light.svg",
        alt: "Create T3 App",
      },
    ],
  },
};

interface Props {
  children: React.ReactNode;
}

const RootLayout: React.FC<Props> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider headers={headers()}>{children}</TRPCReactProvider>
      </body>
    </html>
  );
};

export default RootLayout;
